version: "3.9"
services:
  trezor-user-env-unix:
    image: ghcr.io/trezor/trezor-user-env:bc4d202ed4be726145d61a6afad1c5754b3726d7
    environment:
      - SDL_VIDEODRIVER=dummy
      - XDG_RUNTIME_DIR=/var/tmp
    network_mode: host

  electrum-regtest:
    image: ghcr.io/trezor/electrs:latest
    volumes:
      - ../:/trezor-suite
    network_mode: service:trezor-user-env-unix
